DATA SEGMENT USE16
MENSAGEM DB "Hello World", '$'
DATA ENDS
CODE SEGMENT USE16
    ASSUME CS:CODE,DS:DATA
BEG:
    MOV AX,DATA
    MOV DS,AX
    MOV AH, 9
    MOV DX, OFFSET MENSAGEM
    INT 21H
    MOV AH, 4CH
    INT 21H
CODE ENDS
END BEG