# -*- coding: utf-8 -*-
"""TrabalhoAdrianaFinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16pEBtu0Sn0Y8TzOyw_adS5o72I4n9-RD

# **Análise Algoritmos de Recomendação de Filmes**

A análise será conduzida para avaliar e comparar o desempenho de dois algoritmos de recomendação distintos: **User-Based** e **Content-Based**. Serão exploradas métricas como acurácia, precisão e revocação para medir a eficácia de cada modelo, possibilitando uma visão clara sobre a qualidade das recomendações geradas.

Import das bibliotecas utilizadas
"""

# Responsável por manipular dados
import pandas as pd
# Responsável por implementar os algoritmos
import sklearn.metrics.pairwise as pw
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

"""Leitura dos DataSet utilizados"""

# CSV Filmes
Filmes = pd.read_csv('movies.csv', sep = ',')
# CSV Ratings
Ratings = pd.read_csv('ratings.csv', sep = ',')
# CSV Links
Links = pd.read_csv('links.csv', sep = ',')
# CSV Tags
Tags = pd.read_csv('tags.csv', sep = ',')

# Impressão das primeiras cinco linhas do CSV Filmes
Filmes.head()

# Impressão das primeiras cinco linhas do CSV Ratings
Ratings.head()

# Impressão das primeiras cinco linhas do CSV Links
Links.head()

# Impressão das primeiras cinco linhas do CSV Tags
Tags.head()

# Juntado o CSV Ratings ao CSV Filmes
df = Filmes.merge(Ratings, on = 'movieId')
df.head()

"""# **Implementação do Algoritmo Baseado em Usuário (User-Based)**

O algoritmo de recomendação baseado em usuários (User-Based) utiliza as avaliações atribuídas por cada usuário para construir um perfil de preferência. Com isso, é possível mapear um conjunto de filmes que um usuário específico provavelmente se interessará em assistir, com base nas semelhanças com outros usuários.
"""

# Criação da tabela do DataSet Filmes(já agregado com o Ratings) para manipulação no algoritmo
tabela_filmes = pd.pivot_table(df, index='title', columns='userId', values='rating').fillna(0)
tabela_filmes.head()

rec = pw.cosine_similarity(tabela_filmes)
rec_df = pd.DataFrame(rec, columns=tabela_filmes.index, index=tabela_filmes.index)
rec_df.head()

cossine_df = pd.DataFrame(rec_df['Toy Story'].sort_values(ascending=False))
cossine_df.columns = ['Recomendações']
cossine_df.head(20)

"""# **Implementação do Algoritmo Baseado no Contéudo de cada Filme**

O algoritmo de recomendação baseado em conteúdo (Content-Based) utiliza as características dos filmes, como gênero, diretor, elenco, entre outros atributos, para construir um perfil de preferências de cada usuário. A partir desse perfil, o algoritmo identifica e recomenda filmes com características semelhantes aos filmes previamente bem avaliados pelo usuário.
"""

dados = pd.read_csv('Dados.csv', sep=',')
dados.head()

dados.shape

Filmes['movieId'] = Filmes['movieId'].apply(lambda x: str(x))

df2 = Filmes.merge(dados, left_on='title', right_on='Name', how='left')
df2['movieId'] = df2['movieId'].astype(int)
Tags['movieId'] = Tags['movieId'].astype(int)
df2 = df2.merge(Tags, left_on='movieId', right_on='movieId', how='left')
df2['Infos'] = df2['genres'] + str(df2['Directors_Cast']) + str(df2['Discription']) + df2['tag']
df2.head()

vec = TfidfVectorizer()
tfidf = vec.fit_transform(df2['Infos'].apply(lambda x: np.str_(x)))

sim = cosine_similarity(tfidf)
sim

sim_df2 = pd.DataFrame(sim, columns=df2['title'], index=df2['title'])
sim_df2.head()

final_df = pd.DataFrame(sim_df2['La La Land'].sort_values(ascending=False))
final_df.columns = ['Recomendações']
final_df.head(20)

"""# **Análise Exploratória dos Dados**


Análise de Dados dos Algoritmos de Recomendação Baseado em Usuário e em Conteúdo
Após a implementação dos algoritmos de recomendação Baseado em Usuário (User-Based) e Baseado em Conteúdo (Content-Based), é possível realizar uma análise detalhada dos dados gerados para avaliar a eficácia e a precisão de cada modelo. A análise incluirá métricas como acurácia, precisão, revocação e outras que possam oferecer insights sobre a qualidade das recomendações fornecidas pelos modelos.

Import das bibliotecas utilizadas
"""

print("Termienei a geração dos algoritmos")

# Responsável por plotar gráficos
import matplotlib as plt
# Responsável por ferramentas matematicas
import numpy as np
# Responsável por ferramentas estatísticas
import scipy as sp

"""Agora vamos cruzar os dados gerados"""

